import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { supabase } from "@/lib/supabase";
import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.GOOGLE_API_KEY || process.env.GEMINI_API_KEY || "");

export async function GET() {
    try {
        // Authenticate user
        const session = await auth();
        if (!session || !session.user || !session.user.email) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        const userEmail = session.user.email;
        const today = new Date().toLocaleDateString("en-CA", { timeZone: "Asia/Seoul" });

        console.log(`[daily-briefing/get] Fetching briefing for ${userEmail} on ${today}`);

        // Fetch pre-generated briefing from Supabase
        const { data, error } = await supabase
            .from('daily_briefings')
            .select('briefing_data, created_at')
            .eq('email', userEmail)
            .eq('date', today)
            .single();

        if (error && error.code !== 'PGRST116') {
            console.error('[daily-briefing/get] Error fetching briefing:', error);
            return NextResponse.json({ error: 'Failed to fetch briefing' }, { status: 500 });
        }

        // If briefing exists, return it immediately
        if (data) {
            console.log(`[daily-briefing/get] Found pre-generated briefing for ${userEmail}`);
            return NextResponse.json({
                briefing: data.briefing_data,
                generated_at: data.created_at
            });
        }

        // No pre-generated briefing found
        // DO NOT generate on-demand - return a default message instead
        console.log(`[daily-briefing/get] No pre-generated briefing found for ${userEmail} on ${today}`);
        console.log(`[daily-briefing/get] Returning default message. Briefing should be generated by cron job at 5:00 AM KST`);

        // Return a friendly default briefing
        const defaultBriefing = {
            greeting: "좋은 아침이에요! 🌅",
            yesterdayReview: "오늘의 브리핑이 아직 준비되지 않았습니다. 잠시 후 다시 확인해주세요!",
            yesterdayStats: {
                wakeUp: false,
                learning: 0,
                trendBriefing: 0
            },
            trendSummary: [
                "오늘의 트렌드 브리핑이 준비 중입니다.",
                "매일 아침 5시에 자동으로 생성됩니다.",
                "조금만 기다려주세요!",
                "곧 맞춤형 뉴스를 받아보실 수 있습니다.",
                "프로필 설정을 확인해주세요.",
                "더 나은 브리핑을 위해 관심사를 업데이트해보세요."
            ],
            todayFocus: "브리핑이 준비되는 동안 오늘의 목표를 설정해보세요!",
            importantSchedule: {
                time: "09:00",
                title: "브리핑 다시 확인하기",
                type: "reminder"
            },
            closing: "곧 만나요! 🚀"
        };

        return NextResponse.json({
            briefing: defaultBriefing,
            generated_at: new Date().toISOString(),
            is_default: true,
            message: "Briefing not yet generated. Please check back in a few minutes or ensure cron job is configured."
        });

    } catch (error) {
        console.error('[daily-briefing/get] Unexpected error:', error);
        return NextResponse.json({
            error: 'Failed to fetch briefing',
            details: error instanceof Error ? error.message : 'Unknown error'
        }, { status: 500 });
    }
}
